### ISSUE TITLE
Create Collaboration topic in DevHub

### ISSUE THREAD

**Issue by kelpisland** [bcgov/cloud-pathfinder-technology-and-ux#52]
As part of the COVID19 response DSO has asked for a list of collaboration tools.

Will also work in conjunction with ES : Cindy Beaton has reached out wanting to help.

**Comment by lukegonis** [comment]
@sheaphillips 
Feedback from today's call with Don:
- merge SOAR with corporate STRA
- add who is using it and how
- add context: why would you use one over the other? ie. Trello over Asana
- add key contact in gov for people to reach out to (already done, called steward)
- specify active users are gov users
- use positive examples, ie. 'this tool is a great chat tool when audience includes gov and non-gov and sharing non-sensitive info' instead of 'don't use this for sensitive info'
- add field 'data classification approved for'
